// Export Utilities for Stellar Cartographer
// PNG, SVG, JSON, and Markdown export functions

import {
  Star,
  Empire,
  TradeRoute,
  Wormhole,
  GalaxyConfig,
  ExportData,
  SpectralClass,
  BlackHole,
} from '../types';
import { hexToRgba } from '../utils/colorUtils';
import { STAR_TYPES } from '../utils/starTypes';

// ═══════════════════════════════════════════════════════════════════════════
// PNG EXPORT
// ═══════════════════════════════════════════════════════════════════════════

export function exportPNG(
  canvas: HTMLCanvasElement,
  galaxyName: string,
  renderFn: (ctx: CanvasRenderingContext2D, width: number, height: number) => void
): void {
  const scale = 2; // 2x resolution for high quality
  const exportCanvas = document.createElement('canvas');
  exportCanvas.width = canvas.width * scale;
  exportCanvas.height = canvas.height * scale;
  const ctx = exportCanvas.getContext('2d');
  if (!ctx) return;

  ctx.scale(scale, scale);
  renderFn(ctx, canvas.width, canvas.height);

  // Add watermark
  ctx.font = '600 14px "Space Grotesk", sans-serif';
  ctx.fillStyle = 'rgba(255, 255, 255, 0.4)';
  ctx.textAlign = 'left';
  ctx.fillText(galaxyName, 20, 30);
  
  ctx.font = '400 9px "DM Sans", sans-serif';
  ctx.fillStyle = 'rgba(255, 255, 255, 0.25)';
  ctx.fillText('Generated by StellarForge.tools', 20, 45);

  // Download
  const link = document.createElement('a');
  const filename = sanitizeFilename(galaxyName) || 'galaxy';
  link.download = `${filename}_map.png`;
  link.href = exportCanvas.toDataURL('image/png');
  link.click();
}

// ═══════════════════════════════════════════════════════════════════════════
// SVG EXPORT
// ═══════════════════════════════════════════════════════════════════════════

interface SVGExportOptions {
  width: number;
  height: number;
  galaxyName: string;
  stars: Star[];
  backgroundStars: Array<{ x: number; y: number; size: number; brightness: number }>;
  empires: Empire[];
  tradeRoutes: TradeRoute[];
  wormholes: Wormhole[];
  blackHole?: BlackHole | null;
  camera: { x: number; y: number; zoom: number };
  display: {
    showTerritories: boolean;
    showRoutes: boolean;
    showHabitableIndicators: boolean;
    territoryOpacity: number;
  };
  worldToScreen: (x: number, y: number, z: number) => { screenX: number; screenY: number; scale: number; z: number };
}

export function exportSVG(options: SVGExportOptions): void {
  const {
    width: w,
    height: h,
    galaxyName,
    stars,
    backgroundStars,
    empires,
    tradeRoutes,
    wormholes,
    blackHole,
    camera,
    display,
    worldToScreen
  } = options;
  
  const zoom = camera.zoom;

  let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <defs>
    <style>
      .star-label { font-family: 'Space Grotesk', Arial, sans-serif; font-size: 10px; font-weight: 500; }
      .title { font-family: 'Space Grotesk', Arial, sans-serif; font-size: 14px; font-weight: 600; fill: rgba(255,255,255,0.4); }
      .subtitle { font-family: 'DM Sans', Arial, sans-serif; font-size: 9px; fill: rgba(255,255,255,0.25); }
    </style>
  </defs>
  
  <!-- Background -->
  <rect width="100%" height="100%" fill="#050508"/>
  
`;

  // Background stars
  svg += '  <!-- Background Stars -->\n  <g opacity="0.3">\n';
  const parallax = 0.03;
  for (const star of backgroundStars) {
    const sx = (star.x - camera.x * parallax) * 0.4 + w / 2;
    const sy = (star.y - camera.y * parallax) * 0.4 + h / 2;
    svg += `    <circle cx="${sx.toFixed(1)}" cy="${sy.toFixed(1)}" r="${star.size.toFixed(1)}" fill="white" opacity="${star.brightness.toFixed(2)}"/>\n`;
  }
  svg += '  </g>\n\n';

  // Empire territories
  if (display.showTerritories) {
    svg += '  <!-- Empire Territories -->\n';
    const opacity = display.territoryOpacity / 100;

    for (const empire of empires) {
      const center = worldToScreen(empire.centerX, empire.centerY, 0);
      const radius = empire.radius * zoom * center.scale;

      svg += `  <defs>
    <radialGradient id="empire-${empire.id}">
      <stop offset="0%" stop-color="${empire.color}" stop-opacity="${(0.18 * opacity).toFixed(2)}"/>
      <stop offset="40%" stop-color="${empire.color}" stop-opacity="${(0.12 * opacity).toFixed(2)}"/>
      <stop offset="70%" stop-color="${empire.color}" stop-opacity="${(0.06 * opacity).toFixed(2)}"/>
      <stop offset="100%" stop-color="${empire.color}" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <circle cx="${center.screenX.toFixed(1)}" cy="${center.screenY.toFixed(1)}" r="${radius.toFixed(1)}" fill="url(#empire-${empire.id})"/>\n`;
    }
    svg += '\n';
  }

  // Supermassive Black Hole
  if (blackHole) {
    const bhScreen = worldToScreen(blackHole.x, blackHole.y, 0);
    const activityCfg = {
      quiescent: { glowMul: 4, color: '#FFB800', arcs: 2, arcOp: 0.2 },
      active: { glowMul: 8, color: '#FF6B35', arcs: 3, arcOp: 0.35 },
      quasar: { glowMul: 12, color: '#00D4FF', arcs: 4, arcOp: 0.5 },
    }[blackHole.activity];
    const massScale = Math.log10(Math.max(1, blackHole.mass)) / Math.log10(10000);
    const baseR = 6 + massScale * 14;
    const glowR = baseR * activityCfg.glowMul;

    svg += '  <!-- Supermassive Black Hole -->\n';
    svg += `  <defs><radialGradient id="smbh-glow"><stop offset="0%" stop-color="${activityCfg.color}" stop-opacity="0.6"/><stop offset="50%" stop-color="${activityCfg.color}" stop-opacity="0.15"/><stop offset="100%" stop-color="${activityCfg.color}" stop-opacity="0"/></radialGradient></defs>\n`;
    svg += `  <circle cx="${bhScreen.screenX.toFixed(1)}" cy="${bhScreen.screenY.toFixed(1)}" r="${glowR.toFixed(1)}" fill="url(#smbh-glow)"/>\n`;
    // Photon ring
    svg += `  <circle cx="${bhScreen.screenX.toFixed(1)}" cy="${bhScreen.screenY.toFixed(1)}" r="${(baseR * 1.5).toFixed(1)}" fill="none" stroke="${activityCfg.color}" stroke-width="0.8" opacity="0.5"/>\n`;
    // Event horizon
    svg += `  <circle cx="${bhScreen.screenX.toFixed(1)}" cy="${bhScreen.screenY.toFixed(1)}" r="${baseR.toFixed(1)}" fill="#000000"/>\n`;
    svg += '\n';
  }

  // Trade routes
  if (display.showRoutes && tradeRoutes.length > 0) {
    svg += '  <!-- Trade Routes -->\n  <g>\n';
    for (const route of tradeRoutes) {
      if (route.stars.length < 2) continue;

      let pathD = '';
      route.stars.forEach((star, i) => {
        const s = worldToScreen(star.x, star.y, star.z);
        pathD += (i === 0 ? 'M' : 'L') + `${s.screenX.toFixed(1)},${s.screenY.toFixed(1)} `;
      });

      svg += `    <path d="${pathD}" fill="none" stroke="${route.color}" stroke-width="5" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round"/>\n`;
      svg += `    <path d="${pathD}" fill="none" stroke="${route.color}" stroke-width="2.5" stroke-opacity="0.7" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="10,6"/>\n`;
    }
    svg += '  </g>\n\n';
  }

  // Wormholes
  if (display.showRoutes && wormholes.length > 0) {
    svg += '  <!-- Wormholes -->\n  <g>\n';
    for (const wh of wormholes) {
      const sA = worldToScreen(wh.starA.x, wh.starA.y, wh.starA.z);
      const sB = worldToScreen(wh.starB.x, wh.starB.y, wh.starB.z);

      const midX = (sA.screenX + sB.screenX) / 2;
      const midY = (sA.screenY + sB.screenY) / 2;
      const dist = Math.sqrt((sB.screenX - sA.screenX) ** 2 + (sB.screenY - sA.screenY) ** 2);
      const dx = sB.screenX - sA.screenX;
      const dy = sB.screenY - sA.screenY;
      const perpX = -dy / dist * (dist * 0.15);
      const perpY = dx / dist * (dist * 0.15);
      const ctrlX = midX + perpX;
      const ctrlY = midY + perpY;

      const pathD = `M${sA.screenX.toFixed(1)},${sA.screenY.toFixed(1)} Q${ctrlX.toFixed(1)},${ctrlY.toFixed(1)} ${sB.screenX.toFixed(1)},${sB.screenY.toFixed(1)}`;

      svg += `    <path d="${pathD}" fill="none" stroke="${wh.color}" stroke-width="3" stroke-opacity="0.4" stroke-dasharray="${wh.stable ? '2,8' : '1,4'}"/>\n`;

      [sA, sB].forEach(s => {
        svg += `    <circle cx="${s.screenX.toFixed(1)}" cy="${s.screenY.toFixed(1)}" r="4" fill="${wh.color}"/>\n`;
        svg += `    <circle cx="${s.screenX.toFixed(1)}" cy="${s.screenY.toFixed(1)}" r="2" fill="white"/>\n`;
      });
    }
    svg += '  </g>\n\n';
  }

  // Stars
  const sortedStars = [...stars]
    .map(star => {
      const projected = worldToScreen(star.x, star.y, star.z);
      return { ...star, screenX: projected.screenX, screenY: projected.screenY, screenZ: projected.z, scale: projected.scale };
    })
    .sort((a, b) => a.screenZ - b.screenZ);

  svg += '  <!-- Stars -->\n  <g>\n';
  for (const star of sortedStars) {
    if (star.screenX < -30 || star.screenX > w + 30 || star.screenY < -30 || star.screenY > h + 30) continue;

    const baseSize = star.size * star.scale;
    const zoomFactor = Math.pow(zoom, 0.7);
    const size = Math.max(0.3, baseSize * zoomFactor * 0.5);
    const depthFade = Math.max(0.25, Math.min(1, 1 - star.screenZ / 350));
    const totalBrightness = star.brightness * star.luminosity * depthFade;

    // Glow for hot stars
    if (['O', 'B', 'A'].includes(star.type) && star.luminosity > 0.7) {
      const glowSize = size * (3 + star.luminosity * 3);
      svg += `    <circle cx="${star.screenX.toFixed(1)}" cy="${star.screenY.toFixed(1)}" r="${glowSize.toFixed(1)}" fill="${star.color}" opacity="${(0.15 * star.luminosity * depthFade).toFixed(2)}"/>\n`;
    }

    svg += `    <circle cx="${star.screenX.toFixed(1)}" cy="${star.screenY.toFixed(1)}" r="${size.toFixed(2)}" fill="${star.color}" opacity="${totalBrightness.toFixed(2)}"/>\n`;

    if (star.hasHabitable && zoom > 1.2 && display.showHabitableIndicators) {
      svg += `    <circle cx="${star.screenX.toFixed(1)}" cy="${star.screenY.toFixed(1)}" r="${(size + 3).toFixed(1)}" fill="none" stroke="#2ECC71" stroke-width="1" opacity="${(0.5 * depthFade).toFixed(2)}"/>\n`;
    }
  }
  svg += '  </g>\n\n';

  // Labels (only at high zoom)
  if (zoom >= 2.5) {
    svg += '  <!-- Labels -->\n  <g>\n';
    const labeledStars: typeof sortedStars = [];
    const maxLabels = Math.min(30, Math.floor(zoom * 8));

    for (const star of sortedStars) {
      if (labeledStars.length >= maxLabels) break;
      if (!star.hasHabitable && !['O', 'B'].includes(star.type)) continue;
      if (star.screenX < 50 || star.screenX > w - 50 || star.screenY < 50 || star.screenY > h - 50) continue;

      let collides = false;
      for (const labeled of labeledStars) {
        const dx = star.screenX - labeled.screenX;
        const dy = star.screenY - labeled.screenY;
        if (Math.sqrt(dx * dx + dy * dy) < 60) { collides = true; break; }
      }

      if (!collides) {
        const labelColor = star.empire ? star.empire.color : 'rgba(255,255,255,0.5)';
        svg += `    <text x="${star.screenX.toFixed(1)}" y="${(star.screenY + star.size + 12).toFixed(1)}" text-anchor="middle" class="star-label" fill="${labelColor}">${escapeXml(star.name)}</text>\n`;
        labeledStars.push(star);
      }
    }
    svg += '  </g>\n\n';
  }

  // Title watermark
  svg += `  <!-- Title -->
  <text x="20" y="30" class="title">${escapeXml(galaxyName)}</text>
  <text x="20" y="45" class="subtitle">Generated by StellarForge.tools</text>
</svg>`;

  // Download
  const blob = new Blob([svg], { type: 'image/svg+xml' });
  const link = document.createElement('a');
  const filename = sanitizeFilename(galaxyName) || 'galaxy';
  link.download = `${filename}_map.svg`;
  link.href = URL.createObjectURL(blob);
  link.click();
  URL.revokeObjectURL(link.href);
}

// ═══════════════════════════════════════════════════════════════════════════
// JSON EXPORT
// ═══════════════════════════════════════════════════════════════════════════

export function exportJSON(
  galaxyName: string,
  config: GalaxyConfig,
  empires: Empire[],
  tradeRoutes: TradeRoute[],
  wormholes: Wormhole[],
  stars: Star[],
  blackHole?: BlackHole | null,
): void {
  const data: ExportData = {
    meta: {
      generator: 'StellarForge Stellar Cartographer v4',
      seed: config.seed,
      exportedAt: new Date().toISOString()
    },
    galaxyName,
    galaxy: config,
    empires: empires.map(e => ({
      id: e.id,
      name: e.name,
      color: e.color,
      namingStyle: e.namingStyle,
      centerX: e.centerX,
      centerY: e.centerY,
      radius: e.radius
    })),
    tradeRoutes: tradeRoutes.map(r => ({
      id: r.id,
      name: r.name,
      color: r.color,
      stars: r.stars.map(s => ({ id: s.id, name: s.name }))
    })),
    wormholes: wormholes.map(w => ({
      id: w.id,
      name: w.name,
      starA: w.starA.name,
      starB: w.starB.name,
      stable: w.stable
    })),
    notableSystems: stars
      .filter(s => s.hasHabitable)
      .slice(0, 100)
      .map(s => ({
        name: s.name,
        type: s.type,
        empire: s.empire?.name || null
      })),
    ...(blackHole ? {
      blackHole: {
        name: blackHole.name,
        x: blackHole.x,
        y: blackHole.y,
        mass: blackHole.mass,
        activity: blackHole.activity,
      }
    } : {}),
  };

  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const link = document.createElement('a');
  const filename = sanitizeFilename(galaxyName) || 'galaxy';
  link.download = `${filename}_data.json`;
  link.href = URL.createObjectURL(blob);
  link.click();
  URL.revokeObjectURL(link.href);
}

// ═══════════════════════════════════════════════════════════════════════════
// MARKDOWN EXPORT
// ═══════════════════════════════════════════════════════════════════════════

export function exportMarkdown(
  galaxyName: string,
  config: GalaxyConfig,
  empires: Empire[],
  tradeRoutes: TradeRoute[],
  wormholes: Wormhole[],
  stars: Star[],
  blackHole?: BlackHole | null,
): void {
  let md = `# ${galaxyName}\n\n`;
  md += `**Generated by** StellarForge Stellar Cartographer  \n`;
  md += `**Seed:** ${config.seed}  \n`;
  md += `**Type:** ${config.type}  \n`;
  md += `**Stars:** ${config.starCount.toLocaleString()}  \n\n`;

  md += `---\n\n## Empires\n\n`;
  for (const empire of empires) {
    const count = stars.filter(s => s.empire?.id === empire.id).length;
    md += `### ${empire.name}\n`;
    md += `- **Color:** ${empire.color}\n`;
    md += `- **Naming Style:** ${empire.namingStyle}\n`;
    md += `- **Systems:** ${count.toLocaleString()}\n\n`;
  }

  if (tradeRoutes.length > 0) {
    md += `---\n\n## Trade Routes\n\n`;
    for (const route of tradeRoutes) {
      md += `### ${route.name}\n`;
      md += `- **Waypoints:** ${route.stars.map(s => s.name).join(' → ')}\n\n`;
    }
  }

  if (wormholes.length > 0) {
    md += `---\n\n## Wormholes\n\n`;
    for (const wh of wormholes) {
      md += `### ${wh.name}\n`;
      md += `- **Connection:** ${wh.starA.name} ↔ ${wh.starB.name}\n`;
      md += `- **Stability:** ${wh.stable ? 'Stable' : 'Unstable'}\n\n`;
    }
  }

  if (blackHole) {
    md += `---\n\n## Galactic Nucleus\n\n`;
    md += `### ${blackHole.name}\n`;
    md += `- **Mass:** ${blackHole.mass.toLocaleString()}M☉ (million solar masses)\n`;
    md += `- **Activity:** ${blackHole.activity.charAt(0).toUpperCase() + blackHole.activity.slice(1)}\n`;
    md += `- **Position:** (${blackHole.x.toFixed(0)}, ${blackHole.y.toFixed(0)})\n\n`;
  }

  md += `---\n\n## Notable Habitable Systems\n\n`;
  const habitableStars = stars.filter(s => s.hasHabitable).slice(0, 30);
  for (const star of habitableStars) {
    md += `- **${star.name}** — Class ${star.type}`;
    if (star.empire) md += ` (${star.empire.name})`;
    md += `\n`;
  }

  md += `\n---\n\n*These worlds exist in you. Waiting to be found.*\n\n`;
  md += `© 2025-2026 Jason D. Batt, Ph.D. · StellarForge.tools\n`;

  const blob = new Blob([md], { type: 'text/markdown' });
  const link = document.createElement('a');
  const filename = sanitizeFilename(galaxyName) || 'galaxy';
  link.download = `${filename}_documentation.md`;
  link.href = URL.createObjectURL(blob);
  link.click();
  URL.revokeObjectURL(link.href);
}

// ═══════════════════════════════════════════════════════════════════════════
// UTILITIES
// ═══════════════════════════════════════════════════════════════════════════

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
