// World Pics: 501 SVG illustrations from /public/world-pics/
// Auto-categorized by filename keyword for browsing in the icon picker.

export const WORLD_PIC_CATEGORIES = [
  "Planets & Moons",
  "Stars & Cosmos",
  "Space Travel",
  "Creatures & Mythology",
  "Technology & AI",
  "Nature & Elements",
  "Civilization & Culture",
  "Science & Discovery",
  "Miscellaneous",
] as const;

export type WorldPicCategory = (typeof WORLD_PIC_CATEGORIES)[number];

// Keyword → category mappings (checked in order, first match wins)
const CATEGORY_KEYWORDS: { category: WorldPicCategory; keywords: string[] }[] = [
  {
    category: "Planets & Moons",
    keywords: [
      "mercury", "venus", "earth", "mars", "jupiter", "saturn", "uranus",
      "neptune", "pluto", "ceres", "planet", "moon", "crater",
    ],
  },
  {
    category: "Stars & Cosmos",
    keywords: [
      "sun", "star", "comet", "meteor", "eclipse", "black hole",
      "shooting star", "milky way", "solar system", "astrology", "astronomy",
      "constellation", "orion", "lyra", "cygnus", "cassiopeia", "serpens",
      "monoceros", "bootes", "ursa minor", "auriga", "ursa major",
      "ophiuchus", "andromeda", "pisces", "aquarius", "capricorn",
      "sagittarius", "scorpio", "libra", "virgo", "leo", "cancer",
      "gemini", "taurus", "aries", "lacerta", "horologium", "centaurus",
      "triangulum", "volans", "perseus", "crux", "asteroid belt",
      "moon phases", "meteor shower", "day and night",
    ],
  },
  {
    category: "Space Travel",
    keywords: [
      "astronaut", "rocket", "spaceship", "ufo", "space station",
      "space colony", "space capsule", "lander", "buggy", "rover",
      "satellite", "sputnik", "telescope", "observatory", "space-tourism",
      "jetpack", "hover", "space", "moon rover",
    ],
  },
  {
    category: "Creatures & Mythology",
    keywords: [
      "fairy", "cupid", "devil", "angel", "nymph", "goblin", "banshee",
      "ogre", "cyclops", "golem", "dracula", "werewolf", "bigfoot", "yeti",
      "minotaur", "gnome", "oni", "mermaid", "merman", "grim reaper",
      "succubus", "kappa", "jackalope", "harpy", "wendigo", "troll",
      "madremonte", "unicorn", "pegasus", "dragon", "satyr", "medusa",
      "zeus", "poseidon", "hades", "ares", "apollo", "aphrodite", "athena",
      "atlas", "icarus", "anubis", "horus", "faun", "elf", "genie",
      "kraken", "jack-o-lantern", "alien", "creature", "superhero",
    ],
  },
  {
    category: "Technology & AI",
    keywords: [
      "robot", "android", "artificial intelligence", "coding", "drone",
      "hologram", "quantum computing", "machine learning", "deep learning",
      "neural", "chip", "cpu", "smart", "vr glasses", "augmented",
      "biometric", "cloning", "cyborg", "exoskeleton", "teleportation",
      "time machine", "3d", "innovation", "immersive", "cloud computing",
      "binary code", "chat bot", "voice-control", "remote control",
      "keyboard", "laptop", "smartphone", "sensor", "robotic",
      "industrial robot", "medical robot", "blaster", "laser gun",
      "weapon", "control panel",
    ],
  },
  {
    category: "Nature & Elements",
    keywords: [
      "plant", "forest", "waterfall", "volcano", "desert", "mountain",
      "cave", "flower", "trees", "birds", "rose", "branch", "terrarium",
      "nature", "fire", "waterdrop", "wind", "storm", "rainbow", "sand",
      "atmosphere", "bonfire", "snowflake", "sea", "ocean", "wave",
      "beehive", "polar bear", "monkey", "pet", "dove", "wildfire",
      "animal", "mushroom",
    ],
  },
  {
    category: "Civilization & Culture",
    keywords: [
      "church", "castle", "city", "house", "building", "anchor", "compass",
      "map", "helmet", "armor", "soldier", "crown", "shield", "sword",
      "lighthouse", "bridge", "flag", "agreement", "balance", "farming",
      "agriculture", "ancient", "badge", "amulet", "hat", "tshirt",
      "candles", "fishing", "jeep", "yacht", "container", "train",
      "flying car", "bike", "steering wheel", "paper ship", "kite",
      "camping", "hiking", "backpack", "explorer", "signpost", "traveling",
      "hot air balloon", "parachute", "alpinism", "photographer",
      "navigation", "lantern", "door",
    ],
  },
  {
    category: "Science & Discovery",
    keywords: [
      "dna", "science", "brain", "binoculars", "light bulb", "lightbulb",
      "analysis", "scientist", "medical", "x-ray", "bacterial", "elixir",
      "heartbeat", "virus", "diseases", "notebook", "document", "book",
      "calendar", "microscope", "hibernation", "synthetic", "surgery",
      "research",
    ],
  },
];

// All world-pic filenames
export const ALL_WORLD_PICS: string[] = [
  "001-compass.svg",
  "001-factory.svg",
  "001-fairy.svg",
  "001-hologram.svg",
  "001-mercury.svg",
  "001-orion.svg",
  "001-smartphone.svg",
  "002-artificial intelligence.svg",
  "002-cupid.svg",
  "002-fire.svg",
  "002-hurricane symbol.svg",
  "002-lyra.svg",
  "002-mountains.svg",
  "002-underwater-city.svg",
  "002-venus.svg",
  "003-air pollution.svg",
  "003-book.svg",
  "003-brain.svg",
  "003-cygnus.svg",
  "003-devil.svg",
  "003-earth.svg",
  "003-map.svg",
  "003-moon.svg",
  "003-x-ray.svg",
  "004-angel.svg",
  "004-brain.svg",
  "004-cassiopeia.svg",
  "004-control panel.svg",
  "004-environment.svg",
  "004-futuristic.svg",
  "004-key.svg",
  "004-mars.svg",
  "004-space.svg",
  "004-star.svg",
  "005-box.svg",
  "005-church.svg",
  "005-elf.svg",
  "005-hover-transport.svg",
  "005-planet.svg",
  "005-plant.svg",
  "005-poseidon.svg",
  "005-serpens.svg",
  "006-armor.svg",
  "006-brain.svg",
  "006-eye-scan.svg",
  "006-faun.svg",
  "006-monoceros.svg",
  "006-planet.svg",
  "006-ribbons.svg",
  "006-saturn.svg",
  "006-waterfall.svg",
  "007-artificial intelligence.svg",
  "007-astronaut.svg",
  "007-beehive.svg",
  "007-bootes.svg",
  "007-flying.svg",
  "007-hope.svg",
  "007-microbots.svg",
  "007-ogre.svg",
  "007-uranus.svg",
  "007-waste.svg",
  "008-artificial intelligence.svg",
  "008-diamond.svg",
  "008-dove.svg",
  "008-forest.svg",
  "008-neptune.svg",
  "008-nymph.svg",
  "008-satellite.svg",
  "008-ursa minor.svg",
  "009-adventures.svg",
  "009-artificial intelligence.svg",
  "009-auriga.svg",
  "009-biometric identification.svg",
  "009-constellation.svg",
  "009-cyclops.svg",
  "009-humanitarian.svg",
  "009-pluto.svg",
  "009-teleportation.svg",
  "010-android.svg",
  "010-ceres.svg",
  "010-goblin.svg",
  "010-neural.svg",
  "010-plant.svg",
  "010-satellite.svg",
  "010-signpost.svg",
  "010-ursa major.svg",
  "010-wildfire.svg",
  "011-3d-printer.svg",
  "011-badge.svg",
  "011-cloud computing.svg",
  "011-earth.svg",
  "011-hot air balloon.svg",
  "011-ophiuchus.svg",
  "011-sun.svg",
  "011-zeus.svg",
  "012-andromeda.svg",
  "012-binoculars.svg",
  "012-elixir.svg",
  "012-helmet.svg",
  "012-immersive.svg",
  "012-moon.svg",
  "012-poseidon.svg",
  "013-Asteroid.svg",
  "013-balance.svg",
  "013-extreme.svg",
  "013-hades.svg",
  "013-innovation.svg",
  "013-low battery.svg",
  "013-meteorite.svg",
  "013-pisces.svg",
  "013-robot.svg",
  "013-waterdrop.svg",
  "014-alpinism.svg",
  "014-aquarius.svg",
  "014-ares.svg",
  "014-astronaut.svg",
  "014-dna.svg",
  "014-hibernation.svg",
  "014-light bulb.svg",
  "014-meteor.svg",
  "014-rainbow.svg",
  "014-synthetic-food.svg",
  "015-astronaut.svg",
  "015-athena.svg",
  "015-before.svg",
  "015-capricorn.svg",
  "015-comet.svg",
  "015-Holding Hands.svg",
  "015-lantern.svg",
  "015-smart house.svg",
  "015-space.svg",
  "015-wireless.svg",
  "016-apollo.svg",
  "016-artificial intelligence.svg",
  "016-constellation.svg",
  "016-disaster.svg",
  "016-heartbeat.svg",
  "016-life vest.svg",
  "016-memory-transfer.svg",
  "016-robot.svg",
  "016-sagittarius.svg",
  "016-sun.svg",
  "017-3d model.svg",
  "017-aphrodite.svg",
  "017-bridge.svg",
  "017-earth.svg",
  "017-meteorite.svg",
  "017-polar bear.svg",
  "017-sand.svg",
  "017-scorpio.svg",
  "018-atlas.svg",
  "018-brain.svg",
  "018-cloning.svg",
  "018-earth protection.svg",
  "018-libra.svg",
  "018-paper ship.svg",
  "018-parachute.svg",
  "018-planet earth.svg",
  "018-rocket.svg",
  "019-agriculture.svg",
  "019-cyborg.svg",
  "019-flag.svg",
  "019-medusa.svg",
  "019-moon.svg",
  "019-notebook.svg",
  "019-robot-1.svg",
  "019-virgo.svg",
  "020-farming.svg",
  "020-leo.svg",
  "020-navigation.svg",
  "020-peace sign.svg",
  "020-satyr.svg",
  "020-shooting star.svg",
  "020-spaceship.svg",
  "020-weather change.svg",
  "021-branch.svg",
  "021-cancer.svg",
  "021-drone.svg",
  "021-smart-clothing.svg",
  "021-spaceship.svg",
  "021-terrarium.svg",
  "021-ufo.svg",
  "021-volcano eruption.svg",
  "021-werewolf.svg",
  "022-anchor.svg",
  "022-bigfoot.svg",
  "022-coding.svg",
  "022-global warming.svg",
  "022-hiking.svg",
  "022-lacerta.svg",
  "022-robot.svg",
  "022-solar system.svg",
  "022-ufo.svg",
  "023-atmosphere.svg",
  "023-augmented-reality.svg",
  "023-carbon neutral.svg",
  "023-gemini.svg",
  "023-greeting.svg",
  "023-machete.svg",
  "023-problem solving.svg",
  "023-robotic arm.svg",
  "023-space.svg",
  "023-yeti.svg",
  "024-golem.svg",
  "024-hat.svg",
  "024-kite.svg",
  "024-medical-research.svg",
  "024-no plastic.svg",
  "024-satellite.svg",
  "024-scientist.svg",
  "024-taurus.svg",
  "025-aries.svg",
  "025-bike.svg",
  "025-hologram-1.svg",
  "025-hope.svg",
  "025-machine learning.svg",
  "025-minotaur.svg",
  "025-steering wheel.svg",
  "025-telescope.svg",
  "025-ufo.svg",
  "025-virus.svg",
  "026-astrology.svg",
  "026-ecosystem.svg",
  "026-Jack-o-lantern.svg",
  "026-quantum computing.svg",
  "026-robot.svg",
  "026-robotic-arm.svg",
  "026-science.svg",
  "026-space station.svg",
  "026-thermos.svg",
  "026-tshirt.svg",
  "027-analysis.svg",
  "027-calendar.svg",
  "027-container.svg",
  "027-dracula.svg",
  "027-emission.svg",
  "027-floating.svg",
  "027-pluto.svg",
  "027-sputnik.svg",
  "027-telescope.svg",
  "027-weapon.svg",
  "028-cloning.svg",
  "028-diseases.svg",
  "028-hiking boots.svg",
  "028-house.svg",
  "028-kraken.svg",
  "028-machine learning.svg",
  "028-neptune.svg",
  "028-observatory.svg",
  "028-satellite dish.svg",
  "028-smart-house.svg",
  "029-birds.svg",
  "029-decision.svg",
  "029-earth.svg",
  "029-fist.svg",
  "029-kappa.svg",
  "029-meteor shower.svg",
  "029-satellite dish.svg",
  "029-time machine.svg",
  "029-uranus.svg",
  "029-voice-control.svg",
  "030-deep learning.svg",
  "030-earth.svg",
  "030-first aid kit.svg",
  "030-high-speed-train.svg",
  "030-satellite dish.svg",
  "030-saturn.svg",
  "030-teleportation.svg",
  "030-wendigo.svg",
  "030-zero emission.svg",
  "031-alien.svg",
  "031-apple.svg",
  "031-coding.svg",
  "031-eclipse.svg",
  "031-flying-shoes.svg",
  "031-jackalope.svg",
  "031-jupiter.svg",
  "031-lander.svg",
  "031-photographer.svg",
  "031-sea level.svg",
  "032-air.svg",
  "032-artificial intelligence.svg",
  "032-awareness.svg",
  "032-bacterial.svg",
  "032-blaster.svg",
  "032-flying shoes.svg",
  "032-horus.svg",
  "032-mars.svg",
  "032-meteorite.svg",
  "032-transparent.svg",
  "033-anubis.svg",
  "033-crux.svg",
  "033-earth.svg",
  "033-eclipse.svg",
  "033-eco activism.svg",
  "033-lighthouse.svg",
  "033-medical robot.svg",
  "033-rose.svg",
  "033-space-tourism.svg",
  "033-vr glasses.svg",
  "034-cave.svg",
  "034-earth.svg",
  "034-icarus.svg",
  "034-industrial robot.svg",
  "034-resources.svg",
  "034-robot.svg",
  "034-Science fiction.svg",
  "034-shooting star.svg",
  "034-smart-home.svg",
  "034-telescope.svg",
  "035-amulet.svg",
  "035-animal-communication.svg",
  "035-black hole.svg",
  "035-no fossil fuels.svg",
  "035-oni.svg",
  "035-robot.svg",
  "035-space station.svg",
  "035-traveling.svg",
  "035-venus.svg",
  "036-binary code.svg",
  "036-fishing-boat.svg",
  "036-folded.svg",
  "036-gnome.svg",
  "036-lungs.svg",
  "036-mercury.svg",
  "036-rocket launch.svg",
  "036-space colony.svg",
  "036-space.svg",
  "037-alien.svg",
  "037-artificial intelligence.svg",
  "037-desert.svg",
  "037-hot air balloon.svg",
  "037-household.svg",
  "037-mind-transfer.svg",
  "037-planet.svg",
  "037-solar system.svg",
  "037-space station.svg",
  "037-sun.svg",
  "038-ancient.svg",
  "038-genie.svg",
  "038-heart.svg",
  "038-hologram.svg",
  "038-laptop.svg",
  "038-laser gun.svg",
  "038-moon phases.svg",
  "038-robot-2.svg",
  "038-save the earth.svg",
  "038-telescope.svg",
  "039-alien.svg",
  "039-comet.svg",
  "039-contaminated water.svg",
  "039-flower.svg",
  "039-matches.svg",
  "039-mermaid.svg",
  "039-moon rover.svg",
  "039-quantum computing.svg",
  "039-surgery.svg",
  "040-black hole.svg",
  "040-bonfire.svg",
  "040-demon.svg",
  "040-jetpack.svg",
  "040-meteor shower.svg",
  "040-piggy bank.svg",
  "040-robot-assistant.svg",
  "040-smartphone.svg",
  "040-space colony.svg",
  "040-storm.svg",
  "041-buggy car.svg",
  "041-chip.svg",
  "041-flying car.svg",
  "041-harpy.svg",
  "041-hope.svg",
  "041-interaction.svg",
  "041-milky way.svg",
  "041-space colony.svg",
  "041-stop deforestation.svg",
  "041-telescope.svg",
  "042-agreement.svg",
  "042-asteroid belt.svg",
  "042-banshee.svg",
  "042-blaster.svg",
  "042-chat bot.svg",
  "042-earth.svg",
  "042-flashlight.svg",
  "042-headgear.svg",
  "042-toxic.svg",
  "043-astronaut.svg",
  "043-candles.svg",
  "043-drone.svg",
  "043-keyboard.svg",
  "043-merman.svg",
  "043-robot.svg",
  "043-tourist.svg",
  "044-brain.svg",
  "044-crater.svg",
  "044-day and night.svg",
  "044-exoskeleton.svg",
  "044-grim reaper.svg",
  "044-rocket.svg",
  "044-temperature.svg",
  "044-tree.svg",
  "044-underwater-suit.svg",
  "044-yacht.svg",
  "045-astronomy.svg",
  "045-cpu.svg",
  "045-crossed.svg",
  "045-global.svg",
  "045-nature.svg",
  "045-planet.svg",
  "045-soil erosion.svg",
  "045-space capsule.svg",
  "045-troll.svg",
  "045-ufo.svg",
  "046-astronaut.svg",
  "046-brain.svg",
  "046-day.svg",
  "046-door.svg",
  "046-horologium.svg",
  "046-house.svg",
  "046-ozone layer.svg",
  "046-robotic hand.svg",
  "046-satellite.svg",
  "046-unicorn.svg",
  "047-artificial intelligence.svg",
  "047-astronaut.svg",
  "047-backpack.svg",
  "047-centaurus.svg",
  "047-lighthouse.svg",
  "047-pegasus.svg",
  "047-smart glove.svg",
  "047-space.svg",
  "047-synthetic-ecology.svg",
  "047-trees.svg",
  "048-artificial intelligence.svg",
  "048-document.svg",
  "048-dragon.svg",
  "048-earth.svg",
  "048-heart wings.svg",
  "048-jeep.svg",
  "048-robot-3.svg",
  "048-superhero.svg",
  "048-triangulum.svg",
  "049-astronaut.svg",
  "049-camping.svg",
  "049-green city.svg",
  "049-lightbulb.svg",
  "049-pet.svg",
  "049-planet.svg",
  "049-robotic-limb.svg",
  "049-spaceship.svg",
  "049-succubus.svg",
  "049-volans.svg",
  "050-alien.svg",
  "050-artificial intelligence.svg",
  "050-constellation.svg",
  "050-explorer.svg",
  "050-key.svg",
  "050-madremonte.svg",
  "050-monkey.svg",
  "050-perseus.svg",
  "050-remote control.svg",
  "050-weather.svg",
  "050-wind power.svg",
  "cascading 2.svg",
];

/** Extract the display name from a world-pic filename: "007-astronaut.svg" → "Astronaut" */
export function getWorldPicLabel(filename: string): string {
  return filename
    .replace(/^\d+-/, "")
    .replace(/\.svg$/, "")
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/** Categorize a single world-pic filename */
function categorizeWorldPic(filename: string): WorldPicCategory {
  const lower = filename.toLowerCase().replace(/^\d+-/, "").replace(/\.svg$/, "");
  for (const { category, keywords } of CATEGORY_KEYWORDS) {
    for (const kw of keywords) {
      if (lower.includes(kw)) return category;
    }
  }
  return "Miscellaneous";
}

// Pre-computed index: category → filenames
const _categoryIndex = new Map<WorldPicCategory, string[]>();
for (const cat of WORLD_PIC_CATEGORIES) {
  _categoryIndex.set(cat, []);
}
for (const file of ALL_WORLD_PICS) {
  const cat = categorizeWorldPic(file);
  _categoryIndex.get(cat)!.push(file);
}

/** Get all world-pic filenames for a given category */
export function getWorldPicsByCategory(category: WorldPicCategory): string[] {
  return _categoryIndex.get(category) || [];
}

/** Search world-pics by filename keyword */
export function searchWorldPics(query: string): string[] {
  if (!query.trim()) return ALL_WORLD_PICS;
  const lower = query.toLowerCase();
  return ALL_WORLD_PICS.filter((f) => f.toLowerCase().includes(lower));
}

/** Get the category for a world-pic filename */
export function getWorldPicCategory(filename: string): WorldPicCategory {
  return categorizeWorldPic(filename);
}
