/**
 * StellarForge — Tailwind v3 config
 * GENERATED by design/derive.py + design/emit.py. Do not hand-edit.
 *
 * Two kinds of content below: SOLVED tokens (computed from palette.json,
 * change a target in derive.py and re-run) and PRESERVED tokens (this
 * codebase's existing component library — shadcn/ui, Radix, tailwindcss-
 * animate, the Lora writer-register font — which derive.py has no opinion
 * about and must not silently drop). Deleting a PRESERVED block here without
 * first migrating every call site is how a "regenerate" silently breaks
 * every shadcn Button/Dialog/Popover/Card in the app.
 */
import type { Config } from 'tailwindcss';
import tailwindcssAnimate from 'tailwindcss-animate';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: { '2xl': '1400px' },
    },
    extend: {
      colors: {
        // ── PRESERVED: shadcn/ui semantic tokens ── read from CSS custom
        // properties defined in src/index.css's :root/.dark blocks, not from
        // palette.json. Every shadcn primitive under src/components/ui/
        // (Button, Dialog, Popover, Card, Sidebar, Toast, ...) depends on
        // these existing. Removing them is a full design-system migration,
        // not a token regen.
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        glass: 'hsl(var(--glass))',

        // ── Planes: three, never four ──
        'sf-void':             'rgb(var(--sf-void-rgb) / <alpha-value>)',  // #0A0E17
        'sf-surface':          'rgb(var(--sf-surface-rgb) / <alpha-value>)',  // #1B2334
        'sf-surface-elevated': 'rgb(var(--sf-surface-elevated-rgb) / <alpha-value>)',  // #273249

        // ── Text: solved on the lightest plane. ──
        't1':                      'rgb(var(--t1-rgb) / <alpha-value>)',  // #FAFAFA
        't2':                      'rgb(var(--t2-rgb) / <alpha-value>)',  // #C9CDD3
        't3':                      'rgb(var(--t3-rgb) / <alpha-value>)',  // #A7AAB0
        't4':                      'rgb(var(--t4-rgb) / <alpha-value>)',  // #9799A0
        // t5 is DEPRECATED, not removed: nothing new may use it, and it is
        // no longer solved (this literal predates derive.py). Kept only so
        // existing `text-t5` call sites render instead of losing all colour.
        // Remove once the 10-LEGIBILITY.md component pass has migrated every
        // usage to t3/t4.
        't5': 'rgba(255, 255, 255, 0.38)',

        // ── Lines: solid, not alpha ──
        'sf-line-hairline':    'rgb(var(--sf-line-hairline-rgb) / <alpha-value>)',  // #50555E
        'sf-line':             'rgb(var(--sf-line-rgb) / <alpha-value>)',  // #676B75
        'sf-line-interactive': 'rgb(var(--sf-line-interactive-rgb) / <alpha-value>)',  // #787D87
        'sf-line-emphasis':    'rgb(var(--sf-line-emphasis-rgb) / <alpha-value>)',  // #979BA5
        // DEPRECATED alpha borders — same reasoning as t5. sf-line-* above
        // are the replacement; these stay only until every call site moves.
        'sf-border':           'rgba(255, 255, 255, 0.22)',
        'sf-border-strong':    'rgba(255, 255, 255, 0.36)',

        // ── Accents: canonical hue. Fills, borders, icons, large text. ──
        // 'cyan' here is an ALIAS to teal (see derive.py) — legacy cyan
        // #00D4FF was retired product-wide before this package existed
        // (SF-II settled decision #3). Never reintroduce it as a distinct hue.
        'sf-teal':                 'rgb(var(--sf-teal-rgb) / <alpha-value>)',  // #15C17B
        'sf-teal-bright':          'rgb(var(--sf-teal-bright-rgb) / <alpha-value>)',  // #3DFFCD
        'sf-amber':                'rgb(var(--sf-amber-rgb) / <alpha-value>)',  // #FFB800
        'sf-amber-warm':           'rgb(var(--sf-amber-warm-rgb) / <alpha-value>)',  // #FFB347
        'sf-stellar':              'rgb(var(--sf-stellar-rgb) / <alpha-value>)',  // #5B8DEF
        'sf-emerald':              'rgb(var(--sf-emerald-rgb) / <alpha-value>)',  // #00FF88
        'sf-violet':               'rgb(var(--sf-violet-rgb) / <alpha-value>)',  // #9B5DE5
        'sf-crimson':              'rgb(var(--sf-crimson-rgb) / <alpha-value>)',  // #FF3366
        'sf-azure':                'rgb(var(--sf-azure-rgb) / <alpha-value>)',  // #4D9FFF
        'sf-magenta':              'rgb(var(--sf-magenta-rgb) / <alpha-value>)',  // #FF00AA
        'sf-cyan':                 'rgb(var(--sf-cyan-rgb) / <alpha-value>)',  // #15C17B

        // ── Accent text: the ONLY accent values legal for body-size text ──
        'sf-teal-text':            'rgb(var(--sf-teal-text-rgb) / <alpha-value>)',  // #15C17B
        'sf-teal-bright-text':     'rgb(var(--sf-teal-bright-text-rgb) / <alpha-value>)',  // #3DFFCD
        'sf-amber-text':           'rgb(var(--sf-amber-text-rgb) / <alpha-value>)',  // #FFB800
        'sf-amber-warm-text':      'rgb(var(--sf-amber-warm-text-rgb) / <alpha-value>)',  // #FFB347
        'sf-stellar-text':         'rgb(var(--sf-stellar-text-rgb) / <alpha-value>)',  // #6698FC
        'sf-emerald-text':         'rgb(var(--sf-emerald-text-rgb) / <alpha-value>)',  // #00FF88
        'sf-violet-text':          'rgb(var(--sf-violet-text-rgb) / <alpha-value>)',  // #BA7DFF
        'sf-crimson-text':         'rgb(var(--sf-crimson-text-rgb) / <alpha-value>)',  // #FF658B
        'sf-azure-text':           'rgb(var(--sf-azure-text-rgb) / <alpha-value>)',  // #4D9FFF
        'sf-magenta-text':         'rgb(var(--sf-magenta-text-rgb) / <alpha-value>)',  // #FF54D4
        'sf-cyan-text':            'rgb(var(--sf-cyan-text-rgb) / <alpha-value>)',  // #15C17B

        // ── On-accent: label colour for a filled button ──
        'sf-on-teal':              'rgb(var(--sf-on-teal-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-teal-bright':       'rgb(var(--sf-on-teal-bright-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-amber':             'rgb(var(--sf-on-amber-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-amber-warm':        'rgb(var(--sf-on-amber-warm-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-stellar':           'rgb(var(--sf-on-stellar-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-emerald':           'rgb(var(--sf-on-emerald-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-violet':            'rgb(var(--sf-on-violet-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-crimson':           'rgb(var(--sf-on-crimson-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-azure':             'rgb(var(--sf-on-azure-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-magenta':           'rgb(var(--sf-on-magenta-rgb) / <alpha-value>)',  // #0B0F18
        'sf-on-cyan':              'rgb(var(--sf-on-cyan-rgb) / <alpha-value>)',  // #0B0F18

        // ── Primary ROLE. The user chooses this; sf-teal is a meaning. ──
        'sf-primary':        'rgb(var(--sf-primary-rgb) / <alpha-value>)',
        'sf-primary-text':   'rgb(var(--sf-primary-text-rgb) / <alpha-value>)',
        'sf-primary-bright': 'rgb(var(--sf-primary-bright-rgb) / <alpha-value>)',
        'sf-on-primary':     'rgb(var(--sf-on-primary-rgb) / <alpha-value>)',

        // ── States: never opacity ──
        'sf-disabled-bg':   'rgb(var(--sf-disabled-bg-rgb) / <alpha-value>)',  // #151B29
        'sf-disabled-line': 'rgb(var(--sf-disabled-line-rgb) / <alpha-value>)',  // #575C65
        'sf-disabled-text': 'rgb(var(--sf-disabled-text-rgb) / <alpha-value>)',  // #787B81
        'sf-focus':         'rgb(var(--sf-focus-rgb) / <alpha-value>)',  // #3DFFCD

        // ── PRESERVED: scrollbar swatches used outside tokens.css's own
        // .sf-sb rules, and a couple of legacy direct references ──
        'sb-track': 'rgb(var(--sf-void-rgb) / <alpha-value>)',  // #0A0E17
        'sb-thumb': 'rgb(var(--sf-line-rgb) / <alpha-value>)',  // #676B75
        'sb-thumb-hover': 'rgb(var(--sf-line-emphasis-rgb) / <alpha-value>)',  // #979BA5
      },

      fontFamily: {
        // Four core fonts only (SF-II settled decision #3 — Space Grotesk is
        // retired alongside legacy cyan). Never add it back as a fallback.
        display: ['"MD Nichrome"', 'Jura', 'system-ui', 'sans-serif'],
        heading: ['Jura', '"DM Sans"', 'sans-serif'],
        sans:    ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        // PRESERVED — the writer-register voice (Studio Home, editor).
        // Never on campaign/ops chrome. Dropping this silently reverts every
        // `font-serif` call site to Tailwind's generic serif stack.
        serif:   ['Lora', 'Georgia', 'serif'],
      },

      fontWeight: {
        // PRESERVED — extremes only, no bold, matches the design system's
        // own "ultralight vs medium" rule.
        'sf-light': '300',
        'sf-normal': '400',
        'sf-medium': '500',
      },

      // Tracking reduced across the board. Wide tracking under 12px is the
      // single most damaging legibility choice in the old system.
      letterSpacing: { title: '0.06em', wide: '0.12em', ultra: '0.24em' },

      fontSize: {
        // PRESERVED — the base ramp is nudged up one step from Tailwind's
        // defaults; ~1,600 call sites lean on text-xs/text-sm and shrink
        // back to cramped 12/14px if this block is dropped.
        xs:   ['13px', { lineHeight: '1.5' }],
        sm:   ['15px', { lineHeight: '1.55' }],
        base: ['16.5px', { lineHeight: '1.6' }],

        'sf-hero':    ['clamp(48px, 8vw, 88px)', { lineHeight: '1.02', letterSpacing: '0.02em', fontWeight: '300' }],
        'sf-h1':      ['clamp(34px, 5vw, 52px)', { lineHeight: '1.08', letterSpacing: '0.02em', fontWeight: '300' }],
        'sf-h2':      ['clamp(26px, 3vw, 34px)', { lineHeight: '1.2',  letterSpacing: '0.01em', fontWeight: '400' }],
        'sf-h3':      ['22px', { lineHeight: '1.3',  fontWeight: '500' }],
        'sf-body':    ['16px', { lineHeight: '1.6'  }],   // was 15
        'sf-small':   ['14px', { lineHeight: '1.55' }],   // was 13
        'sf-prose':   ['18px', { lineHeight: '1.7'  }],   // the Studio editor
        'sf-mono':    ['12px', { lineHeight: '1.45', letterSpacing: '0.10em' }],  // was 11 / 0.18em
        'sf-eyebrow': ['12px', { lineHeight: '1.3',  letterSpacing: '0.12em', fontWeight: '600' }],
      },

      spacing: {
        'sf-1':'4px','sf-2':'8px','sf-3':'12px','sf-4':'16px','sf-5':'20px',
        'sf-6':'24px','sf-8':'32px','sf-10':'40px','sf-12':'48px','sf-16':'64px',
        'sf-20':'80px','sf-24':'120px',
      },
      minWidth:  { hit: '44px' },
      minHeight: { hit: '44px' },
      maxWidth:  { measure: '68ch', 'measure-wide': '84ch' },

      borderRadius: {
        none: '0',
        'sf-tag': '2px',
        // PRESERVED — zero radius is the target everywhere (10-LEGIBILITY.md,
        // 07-REVIEW-GATES.md), but these still exist on shadcn primitives
        // that haven't been migrated yet. Removing the scale doesn't make
        // call sites zero-radius, it makes them Tailwind's own arbitrary
        // fallback. Migrate usages, then remove.
        lg: 'var(--radius)',
        md: '4px',
        sm: '3px',
        xs: '2px',
      },

      transitionDuration: { fast:'120ms', base:'180ms', slow:'280ms', ambient:'2400ms' },
      // `transition-sf` — the only transition-property in the system. Without
      // this, `transition-base` sets no property and every state change is dead.
      transitionProperty: {
        sf: 'color, background-color, border-color, outline-color, box-shadow, transform, opacity',
      },
      transitionTimingFunction: {
        'sf-out':   'cubic-bezier(0.2, 0, 0, 1)',
        'sf-inout': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'sf-snap':  'cubic-bezier(0.6, 0, 0.1, 1)',
      },

      boxShadow: {
        'sf-glow-teal':    '0 0 24px rgb(var(--sf-primary-bright-rgb) / 0.30)',   // follows the theme's primary
        'sf-glow-amber':   '0 0 20px rgba(255,184,0,0.25)',
        'sf-glow-crimson': '0 0 20px rgba(255,51,102,0.25)',
        'sf-inset-teal':   'inset 0 0 20px rgb(var(--sf-primary-bright-rgb) / 0.08)',
        // Glow is decoration. It may never be the only indicator of a state.
      },

      backdropBlur: { 'sf-panel': '16px', 'sf-side': '20px' },

      backgroundImage: {
        // PRESERVED — shadcn/ui utility, unrelated to the solved palette.
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },

      keyframes: {
        // PRESERVED — Radix's Accordion drives its open/close height off
        // this exact keyframe pair and the --radix-accordion-content-height
        // var it sets. tailwindcss-animate's animate-in/animate-out
        // utilities (used by Dialog, Popover, Select, Sheet, Tooltip, ...)
        // depend on the plugin below, not on keyframes defined here.
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'sf-pulse': { '0%,100%': { opacity: '0.55' }, '50%': { opacity: '1' } },
        'sf-scan':  { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100%)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        shimmer: 'shimmer 2s linear infinite',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'sf-pulse': 'sf-pulse 2.4s ease-in-out infinite',
        'sf-scan':  'sf-scan 6s linear infinite',
      },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
