"""
Emits tokens.css and tailwind.config.ts from palette.json.

Never hand-edit the generated files. Change a target in derive.py, re-run both:
    python3 derive.py && python3 emit.py
"""
import json, pathlib
OUT = pathlib.Path(__file__).parent
# Explicit encoding on both ends: Windows' Path.write_text/read_text default
# to the console's locale codepage (cp1252), not UTF-8. The generated files
# contain non-ASCII glyphs (°, →, ·), so an implicit-encoding write crashes
# mid-emit on Windows before either file is written.
P = json.loads((OUT / 'palette.json').read_text(encoding='utf-8'))

pl, tx, ln, ac, at, on, st = (P['planes'], P['text'], P['line'], P['accent'],
                              P['accent_text'], P['on_accent'], P['state'])

# Measured worst case per token, computed here rather than typed by hand —
# a comment that drifts from the value it describes is worse than no comment.
def _s2l(c):
    c /= 255
    return c/12.92 if c <= 0.04045 else ((c+0.055)/1.055)**2.4
def _lum(h):
    h = h.lstrip('#'); r, g, b = (int(h[i:i+2], 16) for i in (0, 2, 4))
    return 0.2126*_s2l(r) + 0.7152*_s2l(g) + 0.0722*_s2l(b)
def _cr(a, b):
    la, lb = _lum(a), _lum(b); hi, lo = max(la, lb), min(la, lb)
    return (hi+0.05)/(lo+0.05)
def worst(h):
    return min(_cr(h, pl[p]) for p in pl)
W = {k: f"{worst(v):.2f}:1" for k, v in {**tx, **ln}.items()}

# ─────────────────────────── tokens.css ───────────────────────────
css = f"""/*
 * StellarForge — tokens.css
 * GENERATED by design/derive.py + design/emit.py. Do not hand-edit.
 * Every value is solved against a WCAG contrast target in OKLab.
 *
 *   @import "./tokens.css";
 *   @tailwind base; @tailwind components; @tailwind utilities;
 */

/* ───── FONTS ───── */
@font-face {{
  font-family: 'MD Nichrome';
  src: url('/fonts/MDNichrome-Light.woff2') format('woff2');
  font-weight: 300; font-display: swap;
}}
@font-face {{
  font-family: 'MD Nichrome';
  src: url('/fonts/MDNichrome-Regular.woff2') format('woff2');
  font-weight: 400; font-display: swap;
}}

:root {{
  /* ═══ PLANES ═══ three, never four. Each clears 1.22:1 on the one below,
     so a panel edge is visible before any border is drawn. */
  --sf-void:              {pl['void']};
  --sf-surface:           {pl['surface']};
  --sf-surface-elevated:  {pl['elevated']};
  --sf-scrim:             {P['scrim']};   /* behind modals — elevated still reads raised */

  /* ═══ TEXT ═══ every tier solved on the LIGHTEST plane, so one tier works
     on all three. t5 is retired: nothing readable lives below t4. */
  --t1: {tx['t1']};   /* headings, primary          worst case {W['t1']} */
  --t2: {tx['t2']};   /* body copy                  worst case  {W['t2']} */
  --t3: {tx['t3']};   /* secondary, captions        worst case  {W['t3']} */
  --t4: {tx['t4']};   /* micro labels, eyebrows     worst case  {W['t4']} */

  /* ═══ LINES ═══ solid, not alpha. Alpha composites unpredictably over the
     starfield, grain, and video layers; solid values hold everywhere. */
  --sf-line-hairline:     {ln['hairline']};   /* table rules, dividers   {W['hairline']} */
  --sf-line:              {ln['default']};   /* panel edges             {W['default']} */
  --sf-line-interactive:  {ln['interactive']};   /* inputs, buttons  {W['interactive']} — WCAG 1.4.11 */
  --sf-line-emphasis:     {ln['emphasis']};   /* hover, active, selected {W['emphasis']} */

  /* ═══ ACCENTS ═══ two stops each.
     --sf-X       canonical brand hue. Fills, borders, icons, large text.
     --sf-X-text  the ONLY value permitted for accent-coloured body text.
     --sf-on-X    the label colour that sits on a filled --sf-X. */
"""
for k in ac:
    css += f"  --sf-{k}:{' ' * max(1, 16 - len(k))}{ac[k]};\n"
css += "\n"
for k in at:
    if at[k] != ac[k]:
        css += f"  --sf-{k}-text:{' ' * max(1, 11 - len(k))}{at[k]};\n"
    else:
        css += f"  --sf-{k}-text:{' ' * max(1, 11 - len(k))}var(--sf-{k});\n"
css += "\n"
for k in on:
    css += f"  --sf-on-{k}:{' ' * max(1, 13 - len(k))}{on[k]};\n"

css += f"""
  /* ═══ PRIMARY ROLE ═══ the user-chosen accent. Defaults to teal; themes.css
     overrides per [data-theme]. Roles use these, meanings use named hues. */
  --sf-primary:        var(--sf-teal);
  --sf-primary-text:   var(--sf-teal-text);
  --sf-primary-bright: var(--sf-teal-bright);
  --sf-on-primary:     var(--sf-on-teal);

  /* ═══ STATES ═══ disabled is a COLOUR, never opacity. Opacity multiplies
     against whatever sits behind it and guarantees nothing. */
  --sf-disabled-bg:    {st['disabled_bg']};
  --sf-disabled-line:  {st['disabled_line']};
  --sf-disabled-text:  {st['disabled_text']};
  --sf-focus:          {st['focus']};
  --sf-selection-bg:   {st['selection_bg']};

  /* ═══ TYPE ═══ */
  --font-display: 'MD Nichrome', 'Space Grotesk', sans-serif;
  --font-heading: 'Jura', 'DM Sans', sans-serif;
  --font-sans:    'DM Sans', system-ui, sans-serif;
  --font-mono:    'JetBrains Mono', ui-monospace, monospace;

  /* Tracking. Wide tracking below 12px destroys legibility — the old
     11px/0.18em mono eyebrow was the least readable element in the system. */
  --tr-title: 0.06em;
  --tr-wide:  0.12em;   /* was 0.20em */
  --tr-ultra: 0.24em;   /* lockups at 24px+ ONLY */

  /* ═══ TARGETS ═══ minimum comfortable hit area */
  --hit-min: 44px;

  /* ═══ AMBIENT ═══ one dial for every decorative layer. Set to 0 and the
     starfield, grain, texture, and video all vanish. */
  --sf-ambient: 1;

  /* ═══ SCROLLBAR ═══ was #2E3548 on void — 1.4:1, effectively invisible. */
  --sb-track:       {pl['void']};
  --sb-thumb:       {ln['default']};
  --sb-thumb-hover: {ln['emphasis']};
  --sb-width:       10px;
}}

* {{ box-sizing: border-box; }}

html, body {{
  margin: 0;
  background: var(--sf-void);
  color: var(--t2);
  font-family: var(--font-sans);
  font-weight: 400;
  font-size: 16px;          /* was 15px. This is a writing tool. */
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}}

::selection {{ background: var(--sf-selection-bg); color: #FAFAFA; }}

/* ───── FOCUS ─────
   One rule, everything. The old system had hover states but no visible focus,
   which makes the app unusable by keyboard. --sf-focus clears 10:1 on every
   plane, and the offset keeps it legible against filled buttons too. */
:where(a, button, input, select, textarea, summary, [tabindex]):focus-visible {{
  outline: 2px solid var(--sf-focus);
  outline-offset: 2px;
  border-radius: 0;
}}
:where(a, button, input, select, textarea, summary, [tabindex]):focus:not(:focus-visible) {{
  outline: none;
}}

/* ───── FORM DEFAULTS ─────
   Placeholders may never fall below t3. A placeholder IS content until typed. */
::placeholder {{ color: var(--t3); opacity: 1; }}
input, select, textarea {{
  background: var(--sf-surface);
  border: 1px solid var(--sf-line-interactive);
  color: var(--t1);
  border-radius: 0;
  min-height: var(--hit-min);
  font-size: 16px;   /* below 16px, iOS Safari zooms the viewport on focus */
}}
input:hover, select:hover, textarea:hover {{ border-color: var(--sf-line-emphasis); }}
:disabled {{
  background: var(--sf-disabled-bg);
  border-color: var(--sf-disabled-line);
  color: var(--sf-disabled-text);
  cursor: not-allowed;
}}

/* ───── MEASURE ─────
   Unbounded line length is a legibility failure independent of contrast. */
.sf-measure      {{ max-width: 68ch; }}
.sf-measure-wide {{ max-width: 84ch; }}

/* ───── SCROLLBARS ───── */
::-webkit-scrollbar        {{ width: var(--sb-width); height: var(--sb-width); }}
::-webkit-scrollbar-track  {{ background: var(--sb-track); }}
::-webkit-scrollbar-thumb  {{ background: var(--sb-thumb); border: 2px solid var(--sb-track); }}
::-webkit-scrollbar-thumb:hover {{ background: var(--sb-thumb-hover); }}

.sf-sb {{ scrollbar-color: var(--sb-thumb) var(--sb-track); scrollbar-width: thin; }}
.sf-sb::-webkit-scrollbar         {{ width: var(--sb-width); height: var(--sb-width); }}
.sf-sb::-webkit-scrollbar-track   {{ background: var(--sb-track); border: 0; }}
.sf-sb::-webkit-scrollbar-thumb   {{ background: var(--sb-thumb); border: 0; border-radius: 0; }}
.sf-sb::-webkit-scrollbar-thumb:hover {{ background: var(--sb-thumb-hover); }}
.sf-sb--slim::-webkit-scrollbar {{ width: 8px; height: 8px; }}

/* .sf-sb--idle removed. A scrollbar that hides is a scrollbar that fails
   1.4.11 for the 800ms a user spends looking for it. Keep them visible. */

/* ───── AMBIENT LAYERS ─────
   All decorative layers multiply by --sf-ambient so one variable turns the
   whole atmosphere down. Each also has a hard ceiling: ambient chrome may
   never reduce text contrast below its measured value. */
.sf-starfield {{
  position: fixed; inset: 0; z-index: 0; pointer-events: none;
  opacity: calc(0.6 * var(--sf-ambient));
  background:
    radial-gradient(1px 1px at 20% 30%, rgba(255,255,255,0.40), transparent 50%),
    radial-gradient(1px 1px at 40% 70%, rgba(255,255,255,0.30), transparent 50%),
    radial-gradient(1.5px 1.5px at 60% 20%, rgba(119,172,255,0.40), transparent 50%),
    radial-gradient(1px 1px at 80% 50%, rgba(255,255,255,0.30), transparent 50%),
    radial-gradient(1px 1px at 10% 80%, rgba(255,255,255,0.35), transparent 50%),
    radial-gradient(1px 1px at 90% 85%, rgba(21,193,123,0.40), transparent 50%),
    radial-gradient(1px 1px at 50% 95%, rgba(255,255,255,0.25), transparent 50%);
  background-size: 800px 600px;
}}
.sf-grain::before {{
  content: ''; position: fixed; inset: 0; pointer-events: none; z-index: 1;
  opacity: calc(0.03 * var(--sf-ambient));
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='2'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
}}

/* Text over video or imagery ALWAYS gets a scrim. Measured contrast means
   nothing over a moving background. */
.sf-scrim::before {{
  content: ''; position: absolute; inset: 0; pointer-events: none;
  background: linear-gradient(to bottom, rgba(10,14,23,0.55), rgba(10,14,23,0.85));
}}

/* ───── USER PREFERENCES ───── */
[data-contrast="high"] {{
  --t2: var(--t1);
  --t3: {tx['t2']};
  --t4: {tx['t2']};
  --sf-line-hairline:    var(--sf-line-interactive);
  --sf-line:             var(--sf-line-emphasis);
  --sf-line-interactive: var(--sf-line-emphasis);
  --sf-ambient: 0;
}}
[data-ambient="off"] {{ --sf-ambient: 0; }}

@media (prefers-contrast: more) {{
  :root {{
    --t3: {tx['t2']};
    --t4: {tx['t2']};
    --sf-line: var(--sf-line-emphasis);
    --sf-line-interactive: var(--sf-line-emphasis);
    --sf-ambient: 0.4;
  }}
}}
@media (prefers-reduced-transparency: reduce) {{ :root {{ --sf-ambient: 0; }} }}
@media (prefers-reduced-motion: reduce) {{
  *, *::before, *::after {{
    animation-duration: 0.01ms !important; animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important; scroll-behavior: auto !important;
  }}
}}

/* ───── PANEL GLOW ─────
   Teal underline for focal panels. Decoration only — never the sole
   indicator of a state. */
.sf-panel-glow {{ position: relative; }}
.sf-panel-glow::before {{
  content: ''; position: absolute; bottom: 0; left: 10%; right: 10%;
  height: 1px; pointer-events: none;
  background: linear-gradient(to right, transparent,
              color-mix(in srgb, var(--sf-teal-bright) 30%, transparent), transparent);
}}

/* ───── BRACKET DECORATION ───── */
.sf-bracket {{ position: relative; }}
.sf-bracket::before, .sf-bracket::after {{
  content: ''; position: absolute; width: 12px; height: 12px;
  border: 1px solid var(--sf-teal);
}}
.sf-bracket::before {{ top: -1px; left: -1px; border-right: 0; border-bottom: 0; }}
.sf-bracket::after  {{ bottom: -1px; right: -1px; border-left: 0; border-top: 0; }}
"""
(OUT / 'tokens.css').write_text(css, encoding='utf-8')

# ─────────────────────── tailwind.config.ts ───────────────────────
def block(d, prefix='', indent=8):
    pad = ' ' * indent
    return '\n'.join(f"{pad}'{prefix}{k}':{' ' * max(1, 24 - len(prefix) - len(k))}'{v}',"
                     for k, v in d.items())

ts = f"""/**
 * StellarForge — Tailwind v3 config
 * GENERATED by design/derive.py + design/emit.py. Do not hand-edit.
 *
 * Two kinds of content below: SOLVED tokens (computed from palette.json,
 * change a target in derive.py and re-run) and PRESERVED tokens (this
 * codebase's existing component library — shadcn/ui, Radix, tailwindcss-
 * animate, the Lora writer-register font — which derive.py has no opinion
 * about and must not silently drop). Deleting a PRESERVED block here without
 * first migrating every call site is how a "regenerate" silently breaks
 * every shadcn Button/Dialog/Popover/Card in the app.
 */
import type {{ Config }} from 'tailwindcss';
import tailwindcssAnimate from 'tailwindcss-animate';

const config: Config = {{
  darkMode: ['class'],
  content: [
    './pages/**/*.{{ts,tsx}}',
    './components/**/*.{{ts,tsx}}',
    './app/**/*.{{ts,tsx}}',
    './src/**/*.{{ts,tsx}}',
  ],
  prefix: '',
  theme: {{
    container: {{
      center: true,
      padding: '2rem',
      screens: {{ '2xl': '1400px' }},
    }},
    extend: {{
      colors: {{
        // ── PRESERVED: shadcn/ui semantic tokens ── read from CSS custom
        // properties defined in src/index.css's :root/.dark blocks, not from
        // palette.json. Every shadcn primitive under src/components/ui/
        // (Button, Dialog, Popover, Card, Sidebar, Toast, ...) depends on
        // these existing. Removing them is a full design-system migration,
        // not a token regen.
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {{
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        }},
        secondary: {{
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        }},
        destructive: {{
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        }},
        muted: {{
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        }},
        accent: {{
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        }},
        popover: {{
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        }},
        card: {{
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        }},
        sidebar: {{
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        }},
        glass: 'hsl(var(--glass))',

        // ── Planes: three, never four ──
        'sf-void':             '{pl['void']}',
        'sf-surface':          '{pl['surface']}',
        'sf-surface-elevated': '{pl['elevated']}',

        // ── Text: solved on the lightest plane. ──
{block(tx)}
        // t5 is DEPRECATED, not removed: nothing new may use it, and it is
        // no longer solved (this literal predates derive.py). Kept only so
        // existing `text-t5` call sites render instead of losing all colour.
        // Remove once the 10-LEGIBILITY.md component pass has migrated every
        // usage to t3/t4.
        't5': 'rgba(255, 255, 255, 0.38)',

        // ── Lines: solid, not alpha ──
        'sf-line-hairline':    '{ln['hairline']}',
        'sf-line':             '{ln['default']}',
        'sf-line-interactive': '{ln['interactive']}',
        'sf-line-emphasis':    '{ln['emphasis']}',
        // DEPRECATED alpha borders — same reasoning as t5. sf-line-* above
        // are the replacement; these stay only until every call site moves.
        'sf-border':           'rgba(255, 255, 255, 0.22)',
        'sf-border-strong':    'rgba(255, 255, 255, 0.36)',

        // ── Accents: canonical hue. Fills, borders, icons, large text. ──
        // 'cyan' here is an ALIAS to teal (see derive.py) — legacy cyan
        // #00D4FF was retired product-wide before this package existed
        // (SF-II settled decision #3). Never reintroduce it as a distinct hue.
{block(ac, 'sf-')}

        // ── Accent text: the ONLY accent values legal for body-size text ──
{block(at, 'sf-', 8).replace("':", "-text':")}

        // ── On-accent: label colour for a filled button ──
{block(on, 'sf-on-')}

        // ── Primary ROLE. The user chooses this; sf-teal is a meaning. ──
        'sf-primary':        'var(--sf-primary)',
        'sf-primary-text':   'var(--sf-primary-text)',
        'sf-primary-bright': 'var(--sf-primary-bright)',
        'sf-on-primary':     'var(--sf-on-primary)',

        // ── States: never opacity ──
        'sf-disabled-bg':   '{st['disabled_bg']}',
        'sf-disabled-line': '{st['disabled_line']}',
        'sf-disabled-text': '{st['disabled_text']}',
        'sf-focus':         '{st['focus']}',

        // ── PRESERVED: scrollbar swatches used outside tokens.css's own
        // .sf-sb rules, and a couple of legacy direct references ──
        'sb-track': '{pl['void']}',
        'sb-thumb': '{ln['default']}',
        'sb-thumb-hover': '{ln['emphasis']}',
      }},

      fontFamily: {{
        // Four core fonts only (SF-II settled decision #3 — Space Grotesk is
        // retired alongside legacy cyan). Never add it back as a fallback.
        display: ['"MD Nichrome"', 'Jura', 'system-ui', 'sans-serif'],
        heading: ['Jura', '"DM Sans"', 'sans-serif'],
        sans:    ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        // PRESERVED — the writer-register voice (Studio Home, editor).
        // Never on campaign/ops chrome. Dropping this silently reverts every
        // `font-serif` call site to Tailwind's generic serif stack.
        serif:   ['Lora', 'Georgia', 'serif'],
      }},

      fontWeight: {{
        // PRESERVED — extremes only, no bold, matches the design system's
        // own "ultralight vs medium" rule.
        'sf-light': '300',
        'sf-normal': '400',
        'sf-medium': '500',
      }},

      // Tracking reduced across the board. Wide tracking under 12px is the
      // single most damaging legibility choice in the old system.
      letterSpacing: {{ title: '0.06em', wide: '0.12em', ultra: '0.24em' }},

      fontSize: {{
        // PRESERVED — the base ramp is nudged up one step from Tailwind's
        // defaults; ~1,600 call sites lean on text-xs/text-sm and shrink
        // back to cramped 12/14px if this block is dropped.
        xs:   ['13px', {{ lineHeight: '1.5' }}],
        sm:   ['15px', {{ lineHeight: '1.55' }}],
        base: ['16.5px', {{ lineHeight: '1.6' }}],

        'sf-hero':    ['clamp(48px, 8vw, 88px)', {{ lineHeight: '1.02', letterSpacing: '0.02em', fontWeight: '300' }}],
        'sf-h1':      ['clamp(34px, 5vw, 52px)', {{ lineHeight: '1.08', letterSpacing: '0.02em', fontWeight: '300' }}],
        'sf-h2':      ['clamp(26px, 3vw, 34px)', {{ lineHeight: '1.2',  letterSpacing: '0.01em', fontWeight: '400' }}],
        'sf-h3':      ['22px', {{ lineHeight: '1.3',  fontWeight: '500' }}],
        'sf-body':    ['16px', {{ lineHeight: '1.6'  }}],   // was 15
        'sf-small':   ['14px', {{ lineHeight: '1.55' }}],   // was 13
        'sf-prose':   ['18px', {{ lineHeight: '1.7'  }}],   // the Studio editor
        'sf-mono':    ['12px', {{ lineHeight: '1.45', letterSpacing: '0.10em' }}],  // was 11 / 0.18em
        'sf-eyebrow': ['12px', {{ lineHeight: '1.3',  letterSpacing: '0.12em', fontWeight: '600' }}],
      }},

      spacing: {{
        'sf-1':'4px','sf-2':'8px','sf-3':'12px','sf-4':'16px','sf-5':'20px',
        'sf-6':'24px','sf-8':'32px','sf-10':'40px','sf-12':'48px','sf-16':'64px',
        'sf-20':'80px','sf-24':'120px',
      }},
      minWidth:  {{ hit: '44px' }},
      minHeight: {{ hit: '44px' }},
      maxWidth:  {{ measure: '68ch', 'measure-wide': '84ch' }},

      borderRadius: {{
        none: '0',
        'sf-tag': '2px',
        // PRESERVED — zero radius is the target everywhere (10-LEGIBILITY.md,
        // 07-REVIEW-GATES.md), but these still exist on shadcn primitives
        // that haven't been migrated yet. Removing the scale doesn't make
        // call sites zero-radius, it makes them Tailwind's own arbitrary
        // fallback. Migrate usages, then remove.
        lg: 'var(--radius)',
        md: '4px',
        sm: '3px',
        xs: '2px',
      }},

      transitionDuration: {{ fast:'120ms', base:'180ms', slow:'280ms', ambient:'2400ms' }},
      // `transition-sf` — the only transition-property in the system. Without
      // this, `transition-base` sets no property and every state change is dead.
      transitionProperty: {{
        sf: 'color, background-color, border-color, outline-color, box-shadow, transform, opacity',
      }},
      transitionTimingFunction: {{
        'sf-out':   'cubic-bezier(0.2, 0, 0, 1)',
        'sf-inout': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'sf-snap':  'cubic-bezier(0.6, 0, 0.1, 1)',
      }},

      boxShadow: {{
        'sf-glow-teal':    '0 0 24px rgba(61,255,205,0.30)',
        'sf-glow-amber':   '0 0 20px rgba(255,184,0,0.25)',
        'sf-glow-crimson': '0 0 20px rgba(255,51,102,0.25)',
        'sf-inset-teal':   'inset 0 0 20px rgba(61,255,205,0.08)',
        // Glow is decoration. It may never be the only indicator of a state.
      }},

      backdropBlur: {{ 'sf-panel': '16px', 'sf-side': '20px' }},

      backgroundImage: {{
        // PRESERVED — shadcn/ui utility, unrelated to the solved palette.
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      }},

      keyframes: {{
        // PRESERVED — Radix's Accordion drives its open/close height off
        // this exact keyframe pair and the --radix-accordion-content-height
        // var it sets. tailwindcss-animate's animate-in/animate-out
        // utilities (used by Dialog, Popover, Select, Sheet, Tooltip, ...)
        // depend on the plugin below, not on keyframes defined here.
        'accordion-down': {{
          from: {{ height: '0' }},
          to: {{ height: 'var(--radix-accordion-content-height)' }},
        }},
        'accordion-up': {{
          from: {{ height: 'var(--radix-accordion-content-height)' }},
          to: {{ height: '0' }},
        }},
        shimmer: {{
          '0%': {{ backgroundPosition: '-200% 0' }},
          '100%': {{ backgroundPosition: '200% 0' }},
        }},
        pulse: {{
          '0%, 100%': {{ opacity: '1' }},
          '50%': {{ opacity: '0.5' }},
        }},
        'sf-pulse': {{ '0%,100%': {{ opacity: '0.55' }}, '50%': {{ opacity: '1' }} }},
        'sf-scan':  {{ '0%': {{ transform: 'translateY(-100%)' }}, '100%': {{ transform: 'translateY(100%)' }} }},
      }},
      animation: {{
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        shimmer: 'shimmer 2s linear infinite',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'sf-pulse': 'sf-pulse 2.4s ease-in-out infinite',
        'sf-scan':  'sf-scan 6s linear infinite',
      }},
    }},
  }},
  plugins: [tailwindcssAnimate],
}};

export default config;
"""
(OUT / 'tailwind.config.ts').write_text(ts, encoding='utf-8')
print("wrote tokens.css and tailwind.config.ts")
