/**
 * Timeline-specific Markdown export
 * Generates structured Markdown with tracks, events, links
 */

import type { TimelineState, TimelineEvent, TimelineTrack } from "@/lib/timeline/types";
import { EVENT_TYPE_MAP, IMPORTANCE_MAP, TRACK_TYPE_MAP, LINK_TYPE_CONFIG } from "@/lib/timeline/constants";
import { formatDateRange, sortEventsByDate } from "@/lib/timeline/utils";
import { deepStripHtml } from "@/lib/html-utils";

interface TimelineTextOptions {
  worksheetTitle?: string;
  worldName?: string;
  state: TimelineState;
}

export function generateTimelineMarkdown({
  worksheetTitle,
  worldName,
  state,
}: TimelineTextOptions): string {
  const { tracks, events, eventLinks, elementLinks, compressions } = state;
  const lines: string[] = [];
  const sortedTracks = [...tracks].sort((a, b) => a.order - b.order);

  // Header
  lines.push(`# ${worksheetTitle || "Timeline Export"}`);
  lines.push("");
  if (worldName) lines.push(`**World:** ${worldName}`);
  lines.push(`*Exported from StellarForge on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}*`);
  lines.push("");

  // Overview
  const dateRange = getDateRange(events);
  lines.push("## Overview");
  lines.push("");
  lines.push(`- **Tracks:** ${tracks.length}`);
  lines.push(`- **Events:** ${events.length}`);
  if (dateRange) lines.push(`- **Date Range:** ${dateRange}`);
  if (eventLinks.length > 0) lines.push(`- **Causality Links:** ${eventLinks.length}`);
  if (elementLinks.length > 0) lines.push(`- **Element Links:** ${elementLinks.length}`);
  if (compressions.length > 0) lines.push(`- **Compressions:** ${compressions.length}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Tracks summary
  lines.push("## Tracks");
  lines.push("");
  for (const track of sortedTracks) {
    const count = events.filter((e) => e.trackId === track.id).length;
    const typeLabel = TRACK_TYPE_MAP[track.type]?.label || track.type;
    lines.push(`- **${track.name}** (${typeLabel}, ${count} event${count !== 1 ? "s" : ""})`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  // Events by track
  lines.push("## Events by Track");
  lines.push("");

  for (const track of sortedTracks) {
    const trackEvents = sortEventsByDate(events.filter((e) => e.trackId === track.id));
    if (trackEvents.length === 0) continue;

    lines.push(`### ${track.name}`);
    lines.push("");

    // Get top-level events
    const topLevel = trackEvents.filter(
      (e) => !e.parentEventId || !trackEvents.some((te) => te.id === e.parentEventId)
    );

    for (const event of sortEventsByDate(topLevel)) {
      renderEvent(event, trackEvents, lines, 0);
    }

    lines.push("");
  }

  // Causality Links
  if (eventLinks.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## Causality Links");
    lines.push("");

    for (const link of eventLinks) {
      const source = events.find((e) => e.id === link.sourceEventId);
      const target = events.find((e) => e.id === link.targetEventId);
      if (!source || !target) continue;
      const typeLabel = LINK_TYPE_CONFIG[link.linkType]?.label || link.linkType;
      const labelSuffix = link.label ? `, ${link.label}` : "";
      lines.push(`- **${source.name}** → *${typeLabel}* → **${target.name}**${labelSuffix}`);
    }
    lines.push("");
  }

  // Element Links
  if (elementLinks.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## Linked World Elements");
    lines.push("");

    for (const link of elementLinks) {
      const event = events.find((e) => e.id === link.eventId);
      if (!event) continue;
      const toolName = link.toolType.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
      lines.push(`- **${event.name}** ↔ ${link.worksheetTitle} (${toolName})`);
    }
    lines.push("");
  }

  // Compressions
  if (compressions.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## Time Compressions");
    lines.push("");

    for (const c of compressions) {
      const label = c.label ? `: ${c.label}` : "";
      lines.push(`- **${formatYear(c.startYear)}, ${formatYear(c.endYear)}**${label} (${c.style})`);
    }
    lines.push("");
  }

  // General Notes
  if (state.generalNotes) {
    const clean = deepStripHtml(state.generalNotes);
    if (clean.trim()) {
      lines.push("---");
      lines.push("");
      lines.push("## Notes");
      lines.push("");
      lines.push(clean);
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(`*Generated by [StellarForge](https://stellarforge.tools) on ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}

function renderEvent(
  event: TimelineEvent,
  allEvents: TimelineEvent[],
  lines: string[],
  level: number
) {
  const typeConfig = EVENT_TYPE_MAP[event.eventType];
  const importanceConfig = IMPORTANCE_MAP[event.importance];
  const typeLabel = typeConfig?.label || event.eventType;
  const importanceLabel = importanceConfig?.label || event.importance;
  const indent = "  ".repeat(level);
  const heading = level === 0 ? "####" : "-";

  lines.push(
    `${indent}${heading} ${formatDateRange(event)}, ${event.name}`
  );
  lines.push("");
  lines.push(`${indent}**Type:** ${typeLabel} | **Importance:** ${importanceLabel}`);

  if (event.shortDescription) {
    lines.push("");
    lines.push(`${indent}${event.shortDescription}`);
  }

  if (event.extendedDescription) {
    const clean = deepStripHtml(event.extendedDescription);
    if (clean.trim()) {
      lines.push("");
      lines.push(`${indent}> ${clean.split("\n").join(`\n${indent}> `)}`);
    }
  }

  lines.push("");

  // Children
  const children = sortEventsByDate(
    allEvents.filter((e) => e.parentEventId === event.id)
  );
  for (const child of children) {
    renderEvent(child, allEvents, lines, Math.min(level + 1, 2));
  }
}

function getDateRange(events: TimelineEvent[]): string {
  if (events.length === 0) return "";
  let min = Infinity;
  let max = -Infinity;
  for (const e of events) {
    if (e.startYear < min) min = e.startYear;
    const end = e.endYear ?? e.startYear;
    if (end > max) max = end;
  }
  return `${formatYear(min)}, ${formatYear(max)}`;
}

function formatYear(year: number): string {
  const abs = Math.abs(year);
  const sign = year < 0 ? "-" : "";
  if (abs >= 1_000_000) return `${sign}${(abs / 1_000_000).toFixed(1)}M`;
  if (abs >= 10_000) return `${sign}${(abs / 1_000).toFixed(1)}K`;
  return String(year);
}
