import type { DataBurstConfig } from "./types";

/** Per-tool domain data — keyed by tool slug */
export const TOOL_PAGE_BURSTS: Record<string, DataBurstConfig[]> = {
  "environmental-chain-reaction": [
    { content: "CASCADE ANALYSIS // REV 4.2", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "ΔT_surface = +2.1 K (Holocene avg)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "CO₂ = 421 ppm // CH₄ = 1912 ppb", position: { top: "32%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.06 },
    { content: "REF: Lovelock, 1979", position: { top: "50%", right: "2%" }, variant: "coordinates", parallax: -0.08 },
    { content: "ALBEDO: 0.306 (BOND)", position: { top: "66%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
  ],
  "spacecraft-designer": [
    { content: "BERTH: DOCKING BAY ALPHA", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "Δv = 9.4 km/s (LEO insertion)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.08 },
    { content: "TWR = 1.2 // Isp = 311 s (SL)", position: { top: "34%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
    { content: "REF: Tsiolkovsky, 1903", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "PAYLOAD: 22,800 kg (LEO)", position: { top: "68%", left: "1%" }, variant: "margin", parallax: -0.1 },
  ],
  "propulsion-consequences-map": [
    { content: "IMPULSE TRACE // NOMINAL", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "vₑ = 4.5 km/s (bipropellant)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "thrust = 2.279 MN (F-1 engine)", position: { top: "34%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.06 },
    { content: "REF: Oberth, 1929", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.08 },
    { content: "BURN TIME: 165 s (S-IC)", position: { top: "66%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
  ],
  "planetary-profile": [
    { content: "GENESIS // WORLD SURVEY", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "R⊕ = 6,371 km // ρ = 5.514 g/cm³", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "P_rot = 23h 56m 4.1s", position: { top: "34%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.06 },
    { content: "REF: Kepler, Harmonices Mundi, 1619", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.08 },
    { content: "OBLIQUITY: 23.44°", position: { top: "68%", left: "1%" }, variant: "margin", parallax: -0.12 },
  ],
  "space-expansion-modeler": [
    { content: "EXODUS // EXPANSION VECTOR", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "H₀ = 67.4 ± 0.5 km/s/Mpc", position: { top: "18%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.08 },
    { content: "Ω_Λ = 0.6889 // Ω_m = 0.3111", position: { top: "34%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
    { content: "REF: Hubble, 1929", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "t_universe = 13.787 Gyr", position: { top: "66%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.1 },
  ],
  "drake-equation-calculator": [
    { content: "SIGNAL // DEEP SCAN", position: { top: "8%", right: "3%" }, variant: "status", animation: "flicker", parallax: -0.05 },
    { content: "R* = 1.5–3 yr⁻¹ (Milky Way)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "ν_H = 1420.40575 MHz", position: { top: "34%", left: "1%" }, variant: "margin", parallax: -0.08 },
    { content: "REF: Drake, Green Bank, 1961", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "SETI: SCANNING", position: { top: "68%", left: "1%" }, variant: "margin", animation: "flicker", parallax: -0.12 },
  ],
  "xenomythology-framework-builder": [
    { content: "MYTHOS // DECODE ACTIVE", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "ARCHETYPE: THRESHOLD GUARDIAN", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "MOTIF INDEX: ATU 300–749", position: { top: "34%", left: "1%" }, variant: "margin", parallax: -0.08 },
    { content: "REF: Campbell, The Hero with a Thousand Faces, 1949", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "NARRATIVE: MONOMYTH", position: { top: "66%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
  ],
  "evolutionary-biology": [
    { content: "PHYLO // BRANCH ANALYSIS", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "μ = 2.2 × 10⁻⁸ substitutions/bp/gen", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "N_e = 10,000 (human effective)", position: { top: "34%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.06 },
    { content: "REF: Darwin, On the Origin of Species, 1859", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.08 },
    { content: "CLADE: CHORDATA", position: { top: "68%", left: "1%" }, variant: "margin", parallax: -0.12 },
  ],
  "star-system-builder": [
    { content: "ORRERY // SYSTEM SURVEY", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "L☉ = 3.828 × 10²⁶ W", position: { top: "18%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.08 },
    { content: "a = (T²M)^(1/3) [AU, yr, M☉]", position: { top: "34%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
    { content: "REF: Copernicus, De Revolutionibus, 1543", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "BODIES: SCANNING", position: { top: "66%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.1 },
  ],
  "empire-designer": [
    { content: "DOMINION // SECTOR MAP", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "POLITY: TYPE II (KARDASHEV)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "POP: 4.7 × 10¹¹ (est.)", position: { top: "34%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.06 },
    { content: "REF: Asimov, Foundation, 1951", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.08 },
    { content: "EXPANSION RATE: 0.1 ly/yr", position: { top: "68%", left: "1%" }, variant: "margin", parallax: -0.12 },
  ],
  "technology-consequences": [
    { content: "PARADIGM // IMPACT TRACE", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "TRL: 1–9 (NASA SCALE)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "INNOVATION RATE: dT/dt", position: { top: "34%", left: "1%" }, variant: "margin", parallax: -0.08 },
    { content: "REF: Clarke, Profiles of the Future, 1962", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "DISRUPTION INDEX: HIGH", position: { top: "68%", left: "1%" }, variant: "margin", animation: "flicker", parallax: -0.12 },
  ],
  "species-interaction-matrix": [
    { content: "SYMBIOSIS // ECOLOGY SCAN", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "dN₁/dt = r₁N₁(K₁−N₁−α₁₂N₂)/K₁", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "INTERACTION: MUTUALISM (+/+)", position: { top: "34%", left: "1%" }, variant: "margin", parallax: -0.08 },
    { content: "REF: Lotka-Volterra, 1925–1926", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "NICHE WIDTH: σ = 2.4", position: { top: "68%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.12 },
  ],
  "one-big-lie": [
    { content: "AXIOM // DEVIATION ANALYSIS", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "CONFIDENCE: 3σ OUTSIDE BASELINE", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "COHERENCE INDEX: 0.94", position: { top: "34%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.06 },
    { content: "REF: Niven, 'The Laws of Known Space'", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.08 },
    { content: "PLAUSIBILITY: MAINTAINED", position: { top: "68%", left: "1%" }, variant: "margin", parallax: -0.12 },
  ],
  "time-dilation": [
    { content: "PARADOX // CLOCK SYNC", position: { top: "8%", right: "3%" }, variant: "status", animation: "flicker", parallax: -0.05 },
    { content: "γ = 1/√(1 − v²/c²)", position: { top: "18%", left: "1%" }, variant: "margin", parallax: -0.1 },
    { content: "c = 299,792,458 m/s (exact)", position: { top: "34%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.08 },
    { content: "REF: Einstein, Ann. der Physik, 1905", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "FRAME: INERTIAL", position: { top: "66%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
  ],
  "habitable-zone-calculator": [
    { content: "GOLDILOCKS // ZONE SURVEY", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "S_eff(inner) = 1.014 // S_eff(outer) = 0.3507", position: { top: "18%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.08 },
    { content: "T_eq = 255 K (Earth, no GHG)", position: { top: "34%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
    { content: "REF: Kasting et al., 1993", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "ZONE: CONSERVATIVE HZ", position: { top: "68%", left: "1%" }, variant: "margin", parallax: -0.1 },
  ],
  "lexdrift": [
    { content: "LEXDRIFT // GLOTTOCHRONOLOGY", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "λ(t) = e^(−0.217t) [Swadesh]", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "COGNATE RETENTION: 86% / kyr", position: { top: "34%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.06 },
    { content: "REF: Swadesh, 1952", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.08 },
    { content: "PROTO-LANG: RECONSTRUCTED", position: { top: "66%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
  ],
  "surface-gravity-calculator": [
    { content: "PLUMB // GRAVIMETRY", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "g⊕ = 9.80665 m/s² (standard)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "G = 6.674 × 10⁻¹¹ N·m²/kg²", position: { top: "34%", left: "1%" }, variant: "margin", parallax: -0.08 },
    { content: "REF: Cavendish, 1798", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "TIDAL LOCK: COMPUTING", position: { top: "68%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.12 },
  ],
  "timeline": [
    { content: "CHRONOLOG // TIMELINE ACTIVE", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "Δt = 13.787 Gyr (universe)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.08 },
    { content: "EPOCH: CURRENT ERA", position: { top: "34%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
    { content: "REF: Sagan, Cosmic Calendar, 1977", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "RESOLUTION: 1 Myr", position: { top: "66%", left: "1%" }, variant: "margin", parallax: -0.1 },
  ],
  "sensorium": [
    { content: "SENSORIUM // PERCEPTION MAP", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "λ_vis = 380–700 nm (human)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.1 },
    { content: "f_aud = 20 Hz–20 kHz (human)", position: { top: "34%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.06 },
    { content: "REF: von Uexküll, Umwelt und Innenwelt, 1909", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.08 },
    { content: "UMWELT: MAPPING", position: { top: "68%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
  ],
  "gravitas": [
    { content: "GRAVITAS // FIELD ANALYSIS", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "g_Jupiter = 24.79 m/s² (2.528 g⊕)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.08 },
    { content: "Roche limit = 2.456 R(ρ_M/ρ_m)^(1/3)", position: { top: "34%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
    { content: "REF: Newton, Principia, 1687", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "FIELD STRENGTH: VARIABLE", position: { top: "68%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.1 },
  ],
  "kardashev-scale": [
    { content: "K-SCALE // CLASSIFICATION", position: { top: "8%", right: "3%" }, variant: "status", parallax: -0.05 },
    { content: "P⊕ = 1.8 × 10¹³ W (2025)", position: { top: "18%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.08 },
    { content: "K = (log₁₀P − 6) / 10 [Sagan]", position: { top: "34%", left: "1%" }, variant: "margin", animation: "breathe", parallax: -0.12 },
    { content: "REF: Kardashev, Soviet Astronomy, 1964", position: { top: "52%", right: "2%" }, variant: "coordinates", parallax: -0.06 },
    { content: "L☉ = 3.828 × 10²⁶ W", position: { top: "68%", left: "1%" }, variant: "margin", animation: "live", parallax: -0.1 },
  ],
};
